import Head from "next/head";
import React from "react";
import BookHoliday from "../components/BookHoliday";
import ContactContainer from "../components/ContactContainer";
import MainContainer from "../components/Maincontainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tourister</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer/>
      <BookHoliday/>
       <ContactContainer/>
    </>
  );
}
